model:
  name: 'xgboost'
  max_depth: 40
  objective: 'binary:logistic'
  eval_metric: 'map'
  verbosity: 2
  nthread: 50
  tree_method: "hist"
  grow_policy: 'depthwise'
  subsample: 0.8
  colsample_bytree: 0.8
  num_boost_round: 100
train:
  early_stopping_rounds: 15
  pq_groups_numbers: [0, 1, 2, 3, 4,  5, 6,  7, 8,  9, 10, 11, 12, 13]
  target_scale_pos_weight: 25
featurizer:
  name: 'circular_fingerprint'
  radius: 3
  length: 1024