model:
  name: 'xgboost'
  eta: 0.05
  max_depth: 10
  objective: 'binary:logistic'
  eval_metric: 'map'
  verbosity: 2
  nthread: 50
  tree_method: "hist"
  grow_policy: 'depthwise'
  subsample: 0.6
  colsample_bytree: 0.6
  num_boost_round: 100
  alpha: 0.05
  device: 'cpu'
train:
  early_stopping_rounds: 5
  train_size: 26000000
featurizer:
  name: 'circular_fingerprint'
  radius: 3
  length: 1024