model:
  name: 'xgboost_ensemble'
  weak_learner_config_path: 'binding_prediction/config/yamls/xgboost_config.yaml'
  max_depth: 15
  objective: 'binary:logistic'
  eval_metric: 'map'
  verbosity: 2
  nthread: 12
  tree_method: "hist"
  grow_policy: 'depthwise'
  subsample: 0.5
  colsample_bytree: 0.8
  num_boost_round: 100
train:
  early_stopping_rounds: 5
featurizer:
  name: 'ensemble_predictions'
  num_pq_groups_per_weak_learner: 10
